- name: installing
  pacman:
    name: zsh

- name: installing configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".zsh", ".zinit", ".zshrc", ".zprofile" ] }}'
