- name: install
  pacman:
    name: zsh

- name: install configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".zsh", ".zinit", ".zshrc", ".zprofile" ] }}'
