- name: install emacs
  yay:
    name: emacs-native-comp-git
    state: latest

- name: symlink configuration file
  file:
    src: '{{ role_path }}/files/.emacs.d/'
    path: '~/.emacs.d'
    state: link
    force: yes

- name: installing language servers through pip
  pip:
    name: '{{ pip_lsp_dependencies }}'

- name: install dependencies through npm
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ npm_lsp_dependencies }}'
  become: true
