- name: installing
  yay:
    name: '{{ software }}'
    state: latest

- name: installing configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ files }}'
