- name: install neovim
  pacman:
    name: 'neovim'

- name: install configuration files
  file:
    src: '{{ role_path }}/files/.config/nvim'
    path: '~/.config/nvim'
    state: link
    force: yes

- name: install package manager
  command:
    cmd: git clone --depth 1 https://github.com/wbthomason/packer.nvim  ~/.local/share/nvim/site/pack/packer/start/packer.nvim


- name: install neovim plugins
  command:
    cmd: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerCompile' -c 'PackerSync'
