- name: install dependencies
  yay:
    name: '{{ dependencies }}'
    state: latest

- name: compile and install from source
  make:
    target: install
    chdir: '{{ role_path}}/files/neovim'
    params:
      CMAKE_BUILD_TYPE: RelWithDebInfo
  become: yes

- name: symlink configuration files
  file:
    src: '{{ role_path }}/files/{{ item }}'
    path: '~/{{ item }}'
    state: link
    force: yes
  loop: '{{ [ ".config/nvim" ] }}'

- name: install neovim extensions
  command:
    cmd: nvim +PlugInstall -cqa

- name: install treesitter extensions
  command:
    cmd: nvim +TSInstallSync go python cpp lua -cqa

- name: installing language servers through yay
  yay:
    name: '{{ aur_lsp_dependencies }}'
    state: latest

- name: installing language servers through pip
  pip:
    name: '{{ pip_lsp_dependencies }}'

- name: installing language servers through npm
  npm:
    name: '{{ item }}'
    global: yes
  with_items: '{{ npm_lsp_dependencies }}'
  become: true
