- name: install neovim
  pacman:
    name: 'neovim'

- name: install configuration files
  file:
    src: '{{ role_path }}/files/.config/nvim'
    path: '~/.config/nvim'
    state: link
    force: yes

- name: install neovim plugins
  command:
    cmd: nvim --headless -c 'autocmd User PackerComplete quitall' -c 'PackerCompile' -c 'PackerSync'

- name: install language servers through yay
  yay:
    name: '{{ aur_lsp_dependencies }}'
    state: latest

- name: install language servers through pip
  pip:
    name: '{{ pip_lsp_dependencies }}'
